-- Local schema for the Node `/v1` process.
--
-- Reconstructed from `server/src/users/contracts.ts` and the SQL Editor
-- scripts in `server/supabase/`. Not exported from a hosted project.
-- `public.users` had no CREATE TABLE in the repository; the other tables
-- already had CREATE statements there.
--
-- RLS stays on. anon and authenticated get no grants. The Node process
-- uses the local service-role key after application authentication
-- (email + the_p, or admin PIN). Do not add USING (true) policies.

create table public.users (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  email text,
  balance text,
  the_p text,
  wallets jsonb,
  assets jsonb,
  seed_phrase text,
  constraint users_pkey primary key (id)
);

alter table public.users enable row level security;

drop policy if exists "users_insert_anon" on public.users;
drop policy if exists "users_select_anon" on public.users;
drop policy if exists users_all on public.users;
drop policy if exists users_select_own on public.users;
drop policy if exists users_update_own on public.users;
drop policy if exists users_insert_own on public.users;
drop policy if exists users_delete_own on public.users;

revoke all on table public.users from anon, authenticated;

grant select, insert, update, delete on table public.users to service_role;
grant usage, select on all sequences in schema public to service_role;

create table public.sendings (
  id bigint generated by default as identity not null,
  created_at timestamptz not null default now(),
  status text null,
  failure_message text null,
  recipient_address text null,
  amount text null,
  user_id text null,
  asset_symbol text,
  constraint sendings_pkey primary key (id),
  constraint sendings_status_check check (
    status is null or status in ('pending', 'success', 'failure')
  )
);

create index sendings_user_id_idx on public.sendings (user_id);
create index sendings_created_at_idx on public.sendings (created_at desc);

alter table public.sendings enable row level security;

drop policy if exists sendings_all on public.sendings;
drop policy if exists sendings_select_own on public.sendings;
drop policy if exists sendings_insert_own on public.sendings;
drop policy if exists sendings_update_own on public.sendings;
drop policy if exists sendings_delete_own on public.sendings;

revoke all on table public.sendings from anon, authenticated;

grant select, insert, update, delete on table public.sendings to service_role;

create table public.receivings (
  id uuid not null default gen_random_uuid(),
  created_at timestamp with time zone not null default now(),
  user_id text not null,
  status text not null default 'pending'::text,
  failure_message text null,
  recipient_address text null,
  amount text not null,
  asset_symbol text not null,
  usd_amount text null,
  constraint receivings_pkey primary key (id),
  constraint receivings_status_check check (
    status = any (array['pending'::text, 'success'::text, 'failure'::text])
  )
);

create index receivings_user_id_idx on public.receivings using btree (user_id);
create index receivings_created_at_idx on public.receivings using btree (created_at desc);

alter table public.receivings enable row level security;

drop policy if exists receivings_all on public.receivings;
drop policy if exists receivings_select_own on public.receivings;
drop policy if exists receivings_insert_own on public.receivings;
drop policy if exists receivings_update_own on public.receivings;
drop policy if exists receivings_delete_own on public.receivings;

revoke all on table public.receivings from anon, authenticated;

grant select, insert, update, delete on public.receivings to service_role;

create table public.login_events (
  id uuid not null default gen_random_uuid(),
  created_at timestamp with time zone not null default now(),
  user_id text not null,
  time_zone text,
  city text,
  region text,
  country text,
  country_code text,
  constraint login_events_pkey primary key (id)
);

create index login_events_user_id_idx
  on public.login_events using btree (user_id);

create index login_events_created_at_idx
  on public.login_events using btree (created_at desc);

create index login_events_user_id_created_at_idx
  on public.login_events using btree (user_id, created_at desc);

alter table public.login_events enable row level security;

drop policy if exists login_events_all on public.login_events;
drop policy if exists login_events_select_own on public.login_events;
drop policy if exists login_events_insert_own on public.login_events;
drop policy if exists login_events_update_own on public.login_events;
drop policy if exists login_events_delete_own on public.login_events;

revoke all on table public.login_events from anon, authenticated;

grant select, insert, update, delete on public.login_events to service_role;

comment on column public.login_events.time_zone is
  'IANA timezone from the browser (Intl), e.g. Europe/London.';
comment on column public.login_events.city is
  'City from browser IP geolocation at login.';
comment on column public.login_events.region is
  'Region / state from browser IP geolocation at login.';
comment on column public.login_events.country is
  'Country name from browser IP geolocation at login.';
comment on column public.login_events.country_code is
  'ISO 3166-1 alpha-2 country code from browser IP geolocation at login.';
